# Generated by Django 4.2.18 on 2025-02-24 08:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitemmodel',
            name='address',
        ),
        migrations.RemoveField(
            model_name='orderitemmodel',
            name='city',
        ),
        migrations.RemoveField(
            model_name='orderitemmodel',
            name='state',
        ),
        migrations.RemoveField(
            model_name='orderitemmodel',
            name='zip_code',
        ),
    ]
